name: Twitter Bot

on:
  schedule:
    - cron: "0 9 * * *"  # 毎日9:00に実行
    - cron: "0 20 * * *" # 毎日20:00に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのコードを取得
        uses: actions/checkout@v4

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存関係をインストール
        run: pip install -r requirements.txt

      - name: 環境変数を設定 & 実行
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python bot.py
